### ISSUE TITLE
serviceManagerBuilder.CreateHubContextAsync Issue

### ISSUE THREAD

**Issue by stefanopasu** [fiodarsazanavets/SignalR-on-.NET-6---the-complete-guide#1]
There's an exception in this code

var hubContext = await serviceManager.CreateHubContextAsync<LearningHub>("LearningHub", CancellationToken.None);

Thank you in advance

**Comment by fiodarsazanavets** [comment]
Hi. This repository contains the code samples for the book [SignalR on .NET 6 - the complete guide](https://www.amazon.com/SignalR-NET-Complete-real-time-communication/dp/B09PMFXG5Q). This specific sample is used in the chapter that talks about setting up an Azure SignalR Service.

Have you set up an Azure SignalR Service instance and configured the ASP.NET Core application to connect to it?

**Comment by stefanopasu** [comment]
of course I did.

The issue is that it expect an interface

![image](https://user-images.githubusercontent.com/113413412/189982472-067b0538-fe93-40df-af08-bfd143292170.png)

you could replicate it easily

**Comment by fiodarsazanavets** [comment]
Thank you for pointing this out. I have corrected the code and have re-published the book.
